// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cluster_z_cpp_K
List cluster_z_cpp_K(const List& r_cfg);
RcppExport SEXP _basic_cluster_z_cpp_K(SEXP r_cfgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type r_cfg(r_cfgSEXP);
    rcpp_result_gen = Rcpp::wrap(cluster_z_cpp_K(r_cfg));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_basic_cluster_z_cpp_K", (DL_FUNC) &_basic_cluster_z_cpp_K, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_basic(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
